### ISSUE TITLE
ScalaFiddle.scala:-5: ERROR: Linker used concurrently

### ISSUE THREAD

**Issue by Fraer** [scalafiddle/scalafiddle-editor#23]
ScalaFiddle.scala:-5: ERROR: Linker used concurrently

![scalafiddle](https://cloud.githubusercontent.com/assets/976420/18580550/8977157a-7bfc-11e6-87f6-329361d1a199.jpeg)

Macosx 10.11.5
Chrome Version 53.0.2785.89 (64-bit)

**Comment by sjrd** [comment]
Some Scala.js guru insight: This probably bubbles up all the way from https://github.com/scala-js/scala-js/blob/v0.6.12/tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala#L56 on the server side. It means a single instance of `Linker` is used by two threads concurrently, which is not allowed. So that's probably some synchronization issue on the server.

**Comment by ochrons** [comment]
This does puzzle me a bit, since all compilation is synchronous (going through a single Akka actor) in the compiler server. Also the router sends only a single compilation request at a time to the compiler server. 

The `Linker` is reused between compilations (if the list of dependencies is the same), so perhaps there can be a situation that leaves the `Linker` in some state that it believes it's still active?

If there is an exception while linking, the `Linker` instance will be removed from the cache and not reused.

**Comment by sjrd** [comment]
> If there is an exception while linking, the Linker instance will be removed from the cache and not reused.

Good, because it [can't be reused](https://github.com/scala-js/scala-js/blob/v0.6.12/tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala#L60) :)

Normally, there's a try/finally that makes sure to reset the state saying it's still active (see the above link). I don't see how it could get to a state where it _thinks_ it's still active without actually being still active.

**Comment by ochrons** [comment]
> Good, because it can't be reused :)

Yes, I learned that the hard way ;)

I think I found the issue. The cache is not cleaned correctly, as I added a "fake library" to indicate fast vs full opt. Although still, the error should be different...

**Comment by sjrd** [comment]
Ah! This actually is a good point. If you do call it once after it's been made Invalid (because of a previous exception), it then indeed stays in the state where it thinks it's still active ^^ We should fix this on our side so that the observed error is more explicit.

**Comment by sjrd** [comment]
:+1: 

I'm so glad we have those highly defensive checks at the entrance gate of the `Linker` :-D If that wasn't there, this issue would have never been identified, troubleshooted, nor fixed. It would have remained some obscure heisenbug for all eternity :P
